In [3]:
import pandas as pd
df = pd.read_csv("agg_match_stats_0.csv")

In [4]:
df

,date,game_size,match_id,match_mode,party_size,player_assists,player_dbno,player_dist_ride,player_dist_walk,player_dmg,player_kills,player_name,player_survive_time,team_id,team_placement
0,2017-11-26T20:59:40+0000,37,2U4GBNA0YmnNZYkzjkfgN4ev-hXSrak_BSey_YEG6kIuDG...,tpp,2,0,1,2870.724000,1784.847780,117,1,SnuffIes,1106.320,4,18
1,2017-11-26T20:59:40+0000,37,2U4GBNA0YmnNZYkzjkfgN4ev-hXSrak_BSey_YEG6kIuDG...,tpp,2,0,1,2938.407230,1756.079710,127,1,Ozon3r,1106.315,4,18
2,2017-11-26T20:59:40+0000,37,2U4GBNA0YmnNZYkzjkfgN4ev-hXSrak_BSey_YEG6kIuDG...,tpp,2,0,0,0.000000,224.157562,67,0,bovize,235.558,5,33
3,2017-11-26T20:59:40+0000,37,2U4GBNA0YmnNZYkzjkfgN4ev-hXSrak_BSey_YEG6kIuDG...,tpp,2,0,0,0.000000,92.935150,0,0,sbahn87,197.553,5,33
4,2017-11-26T20:59:40+0000,37,2U4GBNA0YmnNZYkzjkfgN4ev-hXSrak_BSey_YEG6kIuDG...,tpp,2,0,0,2619.077390,2510.447000,175,2,GeminiZZZ,1537.495,14,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13849282,2018-01-04T04:12:58+0000,46,2U4GBNA0YmlWc_jEcSfkfTtWimxqUoNXDijilJ0EXsIlud...,tpp,2,1,1,0.000000,107.555237,187,0,YoungPee,174.608,20,39
13849283,2018-01-04T04:12:58+0000,46,2U4GBNA0YmlWc_jEcSfkfTtWimxqUoNXDijilJ0EXsIlud...,tpp,2,0,0,592.562439,571.859300,51,0,KnightShade_13,355.901,31,29
13849284,2018-01-04T04:12:58+0000,46,2U4GBNA0YmlWc_jEcSfkfTtWimxqUoNXDijilJ0EXsIlud...,tpp,2,0,1,900.445100,454.024000,73,1,XxXRynumXxX,355.896,31,29
13849285,2018-01-04T04:12:58+0000,46,2U4GBNA0YmlWc_jEcSfkfTtWimxqUoNXDijilJ0EXsIlud...,tpp,2,0,1,0.000000,36.453487,99,1,Unknown0311,128.873,35,32
13849286,2018-01-04T04:12:58+0000,46,2U4GBNA0YmlWc_jEcSfkfTtWimxqUoNXDijilJ0EXsIlud...,tpp,2,0,1,0.000000,304.118866,200,2,DoctorHrmm,299.494,35,32

In [7]:
df = pd.read_csv("PUBG.csv"); df

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
0,BreakNeck,4405,3.14,17.65,18469.14,17,3,0.83,4,23.5,...,3751590.99,5194786.58,2626.97,4372.64,536.98,2186,234,1884,242132.73,1448
1,Blackwalk,8199,4.41,18.18,33014.86,33,6,0.36,11,33.3,...,4295917.30,6051783.67,2422.48,6009.73,734.85,2041,276,2340,269795.75,1724
2,mercedes_benz,4454,3.60,0.00,4330.44,5,0,0.00,1,20.0,...,3935265.63,5589608.74,1871.89,3011.87,725.44,1766,210,2193,292977.07,1897
3,DORA,7729,14.00,50.00,13421.82,8,4,0.67,6,75.0,...,2738998.00,3796916.00,2154.62,5578.41,587.28,1214,142,1252,181106.90,1057
4,n2tstar,0,10.50,33.33,9841.04,6,2,0.40,5,83.3,...,2347295.00,3220260.00,2098.47,5642.54,546.10,1245,120,923,160029.80,1077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87893,SaikoMene,87710,1.05,0.00,48273.92,62,0,0.00,5,8.1,...,105321.37,211421.17,1863.11,1503.24,489.84,136,15,70,7285.37,41
87894,KARUKOR,22783,1.61,4.65,49006.75,43,2,0.22,9,20.9,...,98108.14,242154.75,1636.41,1590.67,235.24,143,26,72,14440.64,97
87895,Dertydann,178547,1.00,0.00,14272.20,16,0,0.00,1,6.2,...,177062.72,384254.27,2109.40,1088.12,453.87,157,24,95,15939.11,92
87896,Neferhor,126589,5.10,16.67,58518.86,48,8,0.44,18,37.5,...,523052.83,853232.16,1785.15,1804.51,449.91,397,39,317,56870.07,350
87897,pepperedangus,66362,0.83,1.38,198473.81,217,3,0.03,31,14.3,...,241667.55,500604.73,1638.83,1413.55,363.74,154,28,150,19769.59,140

In [9]:
df.columns.tolist()

['player_name',
 'tracker_id',
 'solo_KillDeathRatio',
 'solo_WinRatio',
 'solo_TimeSurvived',
 'solo_RoundsPlayed',
 'solo_Wins',
 'solo_WinTop10Ratio',
 'solo_Top10s',
 'solo_Top10Ratio',
 'solo_Losses',
 'solo_Rating',
 'solo_BestRating',
 'solo_DamagePg',
 'solo_HeadshotKillsPg',
 'solo_HealsPg',
 'solo_KillsPg',
 'solo_MoveDistancePg',
 'solo_RevivesPg',
 'solo_RoadKillsPg',
 'solo_TeamKillsPg',
 'solo_TimeSurvivedPg',
 'solo_Top10sPg',
 'solo_Kills',
 'solo_Assists',
 'solo_Suicides',
 'solo_TeamKills',
 'solo_HeadshotKills',
 'solo_HeadshotKillRatio',
 'solo_VehicleDestroys',
 'solo_RoadKills',
 'solo_DailyKills',
 'solo_WeeklyKills',
 'solo_RoundMostKills',
 'solo_MaxKillStreaks',
 'solo_WeaponAcquired',
 'solo_Days',
 'solo_LongestTimeSurvived',
 'solo_MostSurvivalTime',
 'solo_AvgSurvivalTime',
 'solo_WinPoints',
 'solo_WalkDistance',
 'solo_RideDistance',
 'solo_MoveDistance',
 'solo_AvgWalkDistance',
 'solo_AvgRideDistance',
 'solo_LongestKill',
 'solo_Heals',
 'solo_Revives',
 'solo_Boosts',
 'solo_DamageDealt',
 'solo_DBNOs',
 'duo_KillDeathRatio',
 'duo_WinRatio',
 'duo_TimeSurvived',
 'duo_RoundsPlayed',
 'duo_Wins',
 'duo_WinTop10Ratio',
 'duo_Top10s',
 'duo_Top10Ratio',
 'duo_Losses',
 'duo_Rating',
 'duo_BestRating',
 'duo_DamagePg',
 'duo_HeadshotKillsPg',
 'duo_HealsPg',
 'duo_KillsPg',
 'duo_MoveDistancePg',
 'duo_RevivesPg',
 'duo_RoadKillsPg',
 'duo_TeamKillsPg',
 'duo_TimeSurvivedPg',
 'duo_Top10sPg',
 'duo_Kills',
 'duo_Assists',
 'duo_Suicides',
 'duo_TeamKills',
 'duo_HeadshotKills',
 'duo_HeadshotKillRatio',
 'duo_VehicleDestroys',
 'duo_RoadKills',
 'duo_DailyKills',
 'duo_WeeklyKills',
 'duo_RoundMostKills',
 'duo_MaxKillStreaks',
 'duo_WeaponAcquired',
 'duo_Days',
 'duo_LongestTimeSurvived',
 'duo_MostSurvivalTime',
 'duo_AvgSurvivalTime',
 'duo_WinPoints',
 'duo_WalkDistance',
 'duo_RideDistance',
 'duo_MoveDistance',
 'duo_AvgWalkDistance',
 'duo_AvgRideDistance',
 'duo_LongestKill',
 'duo_Heals',
 'duo_Revives',
 'duo_Boosts',
 'duo_DamageDealt',
 'duo_DBNOs',
 'squad_KillDeathRatio',
 'squad_WinRatio',
 'squad_TimeSurvived',
 'squad_RoundsPlayed',
 'squad_Wins',
 'squad_WinTop10Ratio',
 'squad_Top10s',
 'squad_Top10Ratio',
 'squad_Losses',
 'squad_Rating',
 'squad_BestRating',
 'squad_DamagePg',
 'squad_HeadshotKillsPg',
 'squad_HealsPg',
 'squad_KillsPg',
 'squad_MoveDistancePg',
 'squad_RevivesPg',
 'squad_RoadKillsPg',
 'squad_TeamKillsPg',
 'squad_TimeSurvivedPg',
 'squad_Top10sPg',
 'squad_Kills',
 'squad_Assists',
 'squad_Suicides',
 'squad_TeamKills',
 'squad_HeadshotKills',
 'squad_HeadshotKillRatio',
 'squad_VehicleDestroys',
 'squad_RoadKills',
 'squad_DailyKills',
 'squad_WeeklyKills',
 'squad_RoundMostKills',
 'squad_MaxKillStreaks',
 'squad_WeaponAcquired',
 'squad_Days',
 'squad_LongestTimeSurvived',
 'squad_MostSurvivalTime',
 'squad_AvgSurvivalTime',
 'squad_WinPoints',
 'squad_WalkDistance',
 'squad_RideDistance',
 'squad_MoveDistance',
 'squad_AvgWalkDistance',
 'squad_AvgRideDistance',
 'squad_LongestKill',
 'squad_Heals',
 'squad_Revives',
 'squad_Boosts',
 'squad_DamageDealt',
 'squad_DBNOs']

In [15]:
df[["solo_KillsPg", "solo_Kills","solo_RoundsPlayed"]].iloc[:10]

   solo_KillsPg  solo_Kills  solo_RoundsPlayed
0          2.59          44                 17
1          3.61         119                 33
2          3.60          18                  5
3          7.00          56                  8
4          7.00          42                  6
5          3.94          63                 16
6          2.24         318                142
7          2.00          38                 19
8          3.18         140                 44
9          3.12          25                  8